version: '3.4'

services:
  download-attachments:
    build:
      context: .
      target: php-cli
    image: ortys4/download-attachments:latest
    volumes:
      - ./dwn:/var/www/html/dwn:rw
      - ./src:/var/www/html/src:rw